# Publish package on main branch if it's tagged with 'v*'

name: Release & publish workflow

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: ["20.x"]

    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build package
        run: |
          pnpm run build
          pnpm install

      - name: Publish package
        run: |
          pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          body: ${{ steps.changelog_reader.outputs.changes }}
          files: dist/*
          draft: false
          prerelease: false
